### PR TITLE
Ukrainian language support

### PR DESCRIPTION
**Pull request by Aboruhen**
Add Ukrainian Support

### CODE REVIEW

**Comment by dorians** [comment]
Thanks a lot for your contribution! :)

**Comment by dorians** [comment]
I've just released new version of Tradukisto with your changes on the board :)
https://mvnrepository.com/artifact/pl.allegro.finance/tradukisto/1.4.0

Thanks a lot!

**Comment by Aboruhen** [comment]
Thanks, I'm gled to help. Also I saw there a lots of code duplication, so
it would be ok, I could try to unify number spelling interface.

**Comment by dorians** [comment]
Yes, that would be awesome! :)

**Pull request merged**
